# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional, Union

from pydantic import Field, SkipValidation
from pydantic.dataclasses import dataclass

from flopy4.mf6.item import Item
from flopy4.mf6.package import CFG, Package
from flopy4.mf6.spec import field, path


@dataclass(config=CFG, kw_only=True)
class Fmi(Package):
    dfn_name: ClassVar[str] = "gwt-fmi"

    @dataclass(config=CFG)
    class Packagedata(Item):
        flowtype: Union[float, str] = field()
        fname: Path = path(converter=Path, direction="in")
        aux: tuple = ()

    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    flow_imbalance_correction: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    packagedata: Optional[SkipValidation[list[Packagedata]]] = field(
        default=None,
        block="packagedata",
    )

FmiPackagedata = Fmi.Packagedata
