# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

from pydantic import Field
from pydantic.dataclasses import dataclass

from flopy4.mf6._types import FloatArrayLike, _optional_path
from flopy4.mf6.package import CFG, Package
from flopy4.mf6.record import Record
from flopy4.mf6.spec import field, path


@dataclass(config=CFG, kw_only=True)
class Ist(Package):
    dfn_name: ClassVar[str] = "gwt-ist"

    multi_package: ClassVar[bool] = True

    @dataclass(config=CFG)
    class Format(Record):
        _keyword: ClassVar[str] = ""
        format_: str = Field()
        columns: Optional[int] = Field(default=None, json_schema_extra={"tagged": True})
        width: Optional[int] = Field(default=None, json_schema_extra={"tagged": True})
        digits: Optional[int] = Field(default=None, json_schema_extra={"tagged": True})

    @dataclass(config=CFG)
    class Cimprint(Record):
        _keyword: ClassVar[str] = "cim"
        _extra_tokens: ClassVar[tuple[str, ...]] = ("PRINT_FORMAT",)
        formatrecord: "Ist.Format" = Field()

    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    budget_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
    )
    budgetcsv_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
    )
    sorption: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
    )
    first_order_decay: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    zero_order_decay: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    cim_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
    )
    cimprint: Optional[Cimprint] = field(
        default=None,
        block="options",
    )
    sorbate_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
    )
    export_array_ascii: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    export_array_netcdf: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    porosity: FloatArrayLike = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
    )
    volfrac: FloatArrayLike = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
    )
    zetaim: FloatArrayLike = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
    )
    cim: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
    )
    decay: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
    )
    decay_sorbed: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
    )
    bulk_density: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
    )
    distcoef: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
    )
    sp2: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
    )
