import argparse
import textwrap
from pathlib import Path
from pprint import pprint
from typing import Iterator

from jinja2 import Environment, FileSystemLoader

from flopy4.dfn import DFN

PROJ_ROOT_PATH = Path(__file__).parents[1]
MODULE_PATH = PROJ_ROOT_PATH / "flopy4"
DFNS_PATH = MODULE_PATH / "dfn"
IDM_PATH = MODULE_PATH / "idm"
TEMPLATES_PATH = MODULE_PATH / "templates"
JINJA_ENV = Environment(loader=FileSystemLoader(TEMPLATES_PATH))


def get_src_name(dfn_path):
    main, sub = dfn_path.stem.split("-")
    return f"{main.title()}{sub.title()}.py"


def generate_py_file(dfn_path, spec) -> Path:
    template = JINJA_ENV.get_template("component.py.j2")
    src_path = IDM_PATH / get_src_name(dfn_path)
    with open(src_path, "w") as f:
        f.write(template.render(**spec))
    return src_path


def generate_sources(dfn_paths) -> Iterator[Path]:
    for path in dfn_paths:
        yield generate_py_file(
            dfn_path=path,
            spec=DFN.load(path),
        )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="Generate Python source files from definition files",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent(
            """\
            Generate a Python interface layer from MF6 definition
            files. This script converts definitions to Python files,
            each representing a parameter set for a particular MF6
            component. Python classes generated by this tool provide
            support for simulations, models or packages described by
            the given definition files. Each file is converted into a
            corresponding Python file with title case and any hyphens
            removed, e.g. `gwf-ic[.dfn/.yml/toml]` becomes `GwfIc.py`.
            """
        ),
    )
    parser.add_argument(
        "-d",
        "--dfn",
        default=DFNS_PATH,
        help="Path to definition file or folder containing definition files",
    )
    parser.add_argument(
        "-o",
        "--outdir",
        default=IDM_PATH,
        help="The directory to write Python source files",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Whether to show verbose output",
    )
    args = parser.parse_args()
    dfn = Path(args.dfn)
    outdir = Path(args.outdir) if args.outdir else Path.cwd()
    verbose = args.verbose

    if dfn.is_file():
        if not dfn.suffix.lower() == ".dfn":
            raise ValueError(f"Expected definition file, got: {dfn}")
    elif dfn.is_dir():
        dfns = [dfn]

    if verbose:
        print("Reading definition files:")
        pprint(dfns)

    srcs = list(generate_sources(dfns))

    if verbose:
        print("Generated Python files:")
        pprint(srcs)
