# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

from pydantic import Field
from pydantic.dataclasses import dataclass

from flopy4.mf6._types import _optional_path
from flopy4.mf6.package import CFG, Package
from flopy4.mf6.spec import field, path


@dataclass(config=CFG, kw_only=True)
class Fmi(Package):
    dfn_name: ClassVar[str] = "prt-fmi"

    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    gwfhead: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="packagedata",
        optional=True,
        direction="in",
    )
    gwfbudget: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="packagedata",
        optional=True,
        direction="in",
    )
    gwfgrid: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="packagedata",
        optional=True,
        direction="in",
    )
