# autogenerated file, do not modify
# ruff: noqa: E501
from typing import ClassVar, Optional

import attrs
import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, dim, field


@xattree(kw_only=True)
class Nam(Package):
    list_: Optional[str] = field(block="options", default=None, longname="name of listing file")
    print_input: bool = field(
        block="options", default=False, longname="print input to listing file"
    )
    print_flows: bool = field(
        block="options", default=False, longname="print calculated flows to listing file"
    )
    save_flows: bool = field(
        block="options", default=False, longname="save flows for all packages to budget file"
    )
    _packages: Optional[dict] = attrs.field(alias="packages", default=None, repr=False)
    npackages: Optional[int] = dim(block="__dim__", coord=False, default=None)
    ftype: Optional[NDArray[np.object_]] = array(
        block="packages",
        dims=("npackages",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="package type",
    )
    fname: Optional[NDArray[np.object_]] = array(
        block="packages",
        dims=("npackages",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="file name",
    )
    pname: Optional[NDArray[np.object_]] = array(
        block="packages",
        dims=("npackages",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="user name for package",
    )
    __block_col_maps__: ClassVar[dict] = {
        "packages": {
            "ftype": "ftype",
            "fname": "fname",
            "pname": "pname",
        },
    }

    def __attrs_post_init__(self):
        if self._packages is not None:
            self._set_block(
                "packages",
                "npackages",
                False,
                {
                    "ftype": "ftype",
                    "fname": "fname",
                    "pname": "pname",
                },
                self._packages,
            )

    @property
    def packages(self):
        return self._get_block(
            {
                "ftype": "ftype",
                "fname": "fname",
                "pname": "pname",
            }
        )

    @packages.setter
    def packages(self, value) -> None:
        self._set_block(
            "packages",
            "npackages",
            False,
            {
                "ftype": "ftype",
                "fname": "fname",
                "pname": "pname",
            },
            value,
        )
