# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional, Union

from pydantic import Field, SkipValidation
from pydantic.dataclasses import dataclass

from flopy4.mf6._types import _optional_path
from flopy4.mf6.item import Item
from flopy4.mf6.package import CFG, Package
from flopy4.mf6.record import Record
from flopy4.mf6.spec import field, path


@dataclass(config=CFG, kw_only=True)
class Oc(Package):
    dfn_name: ClassVar[str] = "prt-oc"

    @dataclass(config=CFG)
    class TrackTimesfile(Record):
        _keyword: ClassVar[str] = "track_timesfile"
        timesfile: str = Field()

    @dataclass(config=CFG)
    class Tracktimes(Item):
        time: float = field()

    @dataclass(config=CFG)
    class All(Item):
        _keyword: ClassVar[str] = "all"

    @dataclass(config=CFG)
    class First(Item):
        _keyword: ClassVar[str] = "first"

    @dataclass(config=CFG)
    class Last(Item):
        _keyword: ClassVar[str] = "last"

    @dataclass(config=CFG)
    class Frequency(Item):
        _keyword: ClassVar[str] = "frequency"
        frequency: int = field()

    @dataclass(config=CFG)
    class Steps(Item):
        _keyword: ClassVar[str] = "steps"
        steps: tuple = field(default=(), array=True)

    @dataclass(config=CFG)
    class Save(Item):
        _keyword: ClassVar[str] = "save"
        rtype: Union[float, str] = field()
        ocsetting: "Oc.All | Oc.First | Oc.Last | Oc.Frequency | Oc.Steps" = field()

    @dataclass(config=CFG)
    class Print(Item):
        _keyword: ClassVar[str] = "print"
        rtype: Union[float, str] = field()
        ocsetting: "Oc.All | Oc.First | Oc.Last | Oc.Frequency | Oc.Steps" = field()

    _StressPeriodDataItem = (
        Save |
        Print
    )

    budget_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
    )
    budgetcsv_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
    )
    track_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
    )
    trackcsv_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
    )
    track_release: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    track_exit: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    track_subfeature_exit: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    track_timestep: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    track_terminate: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    track_weaksink: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    track_usertime: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    track_dropped: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    # TODO: track_timesrecord — type 'record' not yet supported
    track_timesfile: Optional[TrackTimesfile] = field(
        default=None,
        block="options",
    )
    scratch_buffer: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    ntracktimes: Optional[int] = field(
        default=None,
        block="dimensions",
        optional=True,
    )
    tracktimes: Optional[SkipValidation[list[Tracktimes]]] = field(
        default=None,
        block="tracktimes",
        auto_from="tracktimes",
    )
    _stress_period_data: Optional[SkipValidation[dict[int, list[_StressPeriodDataItem]]]] = field(
        alias="stress_period_data",
        default=None,
        repr=False,
        block="period",
        fill_forward=True,
    )

OcTracktimes = Oc.Tracktimes
OcAll = Oc.All
OcFirst = Oc.First
OcLast = Oc.Last
OcFrequency = Oc.Frequency
OcSteps = Oc.Steps
OcSave = Oc.Save
OcPrint = Oc.Print
