# autogenerated file, do not modify
# ruff: noqa: E501
from pathlib import Path
from typing import Optional

import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, dim, field, path
from flopy4.utils import to_path


@xattree(kw_only=True)
class Dis2d(Package):
    length_units: Optional[str] = field(
        block="options", default=None, longname="model length units"
    )
    nogrb: bool = field(block="options", default=False, longname="do not write binary grid file")
    grb_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    xorigin: Optional[float] = field(
        block="options", default=None, longname="x-position of the model grid origin"
    )
    yorigin: Optional[float] = field(
        block="options", default=None, longname="y-position of the model grid origin"
    )
    angrot: Optional[float] = field(block="options", default=None, longname="rotation angle")
    export_array_ascii: bool = field(
        block="options", default=False, longname="export array variables to layered ascii files."
    )
    nrow: Optional[int] = dim(
        block="dimensions", coord=False, default="2", longname="number of rows"
    )
    ncol: Optional[int] = dim(
        block="dimensions", coord=False, default="2", longname="number of columns"
    )
    delr: NDArray[np.float64] = array(
        block="griddata",
        dims=("ncol",),
        default="1.0",
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="spacing along a row",
    )
    delc: NDArray[np.float64] = array(
        block="griddata",
        dims=("nrow",),
        default="1.0",
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="spacing along a column",
    )
    bottom: NDArray[np.float64] = array(
        block="griddata",
        dims=("ncol", "nrow"),
        default="0.",
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="cell bottom elevation",
    )
    idomain: Optional[NDArray[np.int64]] = array(
        block="griddata",
        dims=("ncol", "nrow"),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="idomain existence array",
    )
