# autogenerated file, do not modify
# ruff: noqa: E501
import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, field


@xattree(kw_only=True)
class Sto(Package):
    save_flows: bool = field(block="options", default=False, longname="keyword to save NPF flows")
    export_array_ascii: bool = field(
        block="options", default=False, longname="export array variables to layered ascii files."
    )
    steady_state: Optional[NDArray[np.bool_]] = array(
        block="period",
        dims=("nper",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="steady state indicator",
    )
    transient: Optional[NDArray[np.bool_]] = array(
        block="period",
        dims=("nper",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="transient indicator",
    )
