import argparse
import textwrap
from pathlib import Path
from pprint import pprint

PROJ_ROOT_PATH = Path(__file__).parents[1]
DFNS_PATH = PROJ_ROOT_PATH / "flopy4" / "dfns"
IDM_PATH = PROJ_ROOT_PATH / "flopy4" / "idm"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="Convert DFN files to Python source files",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent(
            """\
            Generate Python source code from DFN files. This script
            converts definition (DFN) files to Python source files,
            each representing a parameter set for a particular input
            definition. Python files generated by this tool provide
            support for simulations, models or packages described by
            the given DFN files. Each DFN file is transformed into a
            corresponding Python file with title case and any hyphens
            removed, e.g. gwf-ic.dfn becomes GwfIc.py.
            """
        ),
    )
    parser.add_argument(
        "-d",
        "--dfn",
        required=False,
        default=DFNS_PATH,
        help="Path to a DFN file or to a directory containing DFN files",
    )
    parser.add_argument(
        "-o",
        "--outdir",
        required=False,
        default=IDM_PATH,
        help="The directory to write Python source files",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        required=False,
        default=False,
        help="Whether to show verbose output",
    )
    args = parser.parse_args()
    dfn = Path(args.dfn)
    outdir = Path(args.outdir) if args.outdir else Path.cwd()
    verbose = args.verbose

    if dfn.is_file():
        if not dfn.suffix.lower() == ".dfn":
            raise ValueError(f"Expected DFN file, got: {dfn}")
    elif dfn.is_dir():
        dfns = [dfn]

    if verbose:
        print("Reading DFNs:")
        pprint(dfns)
        print(f"Generating Python files in: {outdir}")

    # todo: generate
