# autogenerated file, do not modify
# ruff: noqa: E501
from typing import ClassVar, Optional

import attrs
import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, dim, field


@xattree(kw_only=True)
class Cxs(Package):
    print_input: bool = field(
        block="options", default=False, longname="print input to listing file"
    )
    nsections: Optional[int] = dim(
        block="dimensions", coord=False, default=None, longname="number of reaches"
    )
    npoints: Optional[int] = dim(
        block="dimensions",
        coord=False,
        default=None,
        longname="total number of points defined for all reaches",
    )
    _packagedata: Optional[dict] = attrs.field(alias="packagedata", default=None, repr=False)
    idcxs: Optional[NDArray[np.int64]] = array(
        block="packagedata",
        dims=("nsections",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="reach number for this entry",
        cellid=True,
    )
    nxspoints: Optional[NDArray[np.int64]] = array(
        block="packagedata",
        dims=("nsections",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="number of points used to define cross section",
    )
    _crosssectiondata: Optional[dict] = attrs.field(
        alias="crosssectiondata", default=None, repr=False
    )
    xfraction: Optional[NDArray[np.float64]] = array(
        block="crosssectiondata",
        dims=("npoints",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="fractional width",
    )
    height: Optional[NDArray[np.float64]] = array(
        block="crosssectiondata",
        dims=("npoints",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="depth",
    )
    manfraction: Optional[NDArray[np.float64]] = array(
        block="crosssectiondata",
        dims=("npoints",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="Manning's roughness coefficient",
    )
    __block_col_maps__: ClassVar[dict] = {
        "packagedata": {
            "idcxs": "idcxs",
            "nxspoints": "nxspoints",
        },
        "crosssectiondata": {
            "xfraction": "xfraction",
            "height": "height",
            "manfraction": "manfraction",
        },
    }

    def __attrs_post_init__(self):
        if self._packagedata is not None:
            self._set_block(
                "packagedata",
                "nsections",
                True,
                {
                    "idcxs": "idcxs",
                    "nxspoints": "nxspoints",
                },
                self._packagedata,
            )
        if self._crosssectiondata is not None:
            self._set_block(
                "crosssectiondata",
                "npoints",
                True,
                {
                    "xfraction": "xfraction",
                    "height": "height",
                    "manfraction": "manfraction",
                },
                self._crosssectiondata,
            )

    @property
    def packagedata(self):
        return self._get_block(
            {
                "idcxs": "idcxs",
                "nxspoints": "nxspoints",
            }
        )

    @packagedata.setter
    def packagedata(self, value) -> None:
        self._set_block(
            "packagedata",
            "nsections",
            True,
            {
                "idcxs": "idcxs",
                "nxspoints": "nxspoints",
            },
            value,
        )

    @property
    def crosssectiondata(self):
        return self._get_block(
            {
                "xfraction": "xfraction",
                "height": "height",
                "manfraction": "manfraction",
            }
        )

    @crosssectiondata.setter
    def crosssectiondata(self, value) -> None:
        self._set_block(
            "crosssectiondata",
            "npoints",
            True,
            {
                "xfraction": "xfraction",
                "height": "height",
                "manfraction": "manfraction",
            },
            value,
        )
