# autogenerated file, do not modify
# ruff: noqa: E501
from pathlib import Path
from typing import ClassVar, Optional

import attrs
import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, dim, field, path
from flopy4.utils import to_path


@xattree(kw_only=True)
class Disv1d(Package):
    length_units: Optional[str] = field(
        block="options", default=None, longname="model length units"
    )
    nogrb: bool = field(block="options", default=False, longname="do not write binary grid file")
    grb_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    xorigin: Optional[float] = field(
        block="options",
        default=None,
        longname="x-position origin of the model grid coordinate system",
    )
    yorigin: Optional[float] = field(
        block="options",
        default=None,
        longname="y-position origin of the model grid coordinate system",
    )
    angrot: Optional[float] = field(block="options", default=None, longname="rotation angle")
    export_array_ascii: bool = field(
        block="options", default=False, longname="export array variables to layered ascii files."
    )
    nodes: Optional[int] = dim(
        block="dimensions", coord=False, default=None, longname="number of linear features"
    )
    nvert: Optional[int] = dim(
        block="dimensions", coord=False, default=None, longname="number of columns"
    )
    _vertices: Optional[dict] = attrs.field(alias="vertices", default=None, repr=False)
    iv: Optional[NDArray[np.int64]] = array(
        block="vertices",
        dims=("nvert",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="vertex number",
        cellid=True,
    )
    xv: Optional[NDArray[np.float64]] = array(
        block="vertices",
        dims=("nvert",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="x-coordinate for vertex",
    )
    yv: Optional[NDArray[np.float64]] = array(
        block="vertices",
        dims=("nvert",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="y-coordinate for vertex",
    )
    _cell2d: Optional[dict] = attrs.field(alias="cell2d", default=None, repr=False)
    icell2d: Optional[NDArray[np.int64]] = array(
        block="cell2d",
        dims=("nodes",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="cell2d number",
        cellid=True,
    )
    fdc: Optional[NDArray[np.float64]] = array(
        block="cell2d",
        dims=("nodes",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="fractional distance to the cell center",
    )
    ncvert: Optional[NDArray[np.int64]] = array(
        block="cell2d",
        dims=("nodes",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="number of cell vertices",
    )
    icvert: Optional[NDArray[np.int64]] = array(
        block="cell2d",
        dims=("nodes",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="number of cell vertices",
        cellid=True,
    )
    length: NDArray[np.float64] = array(
        block="griddata",
        dims=("nodes",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="length",
    )
    width: NDArray[np.float64] = array(
        block="griddata",
        dims=("nodes",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="width",
    )
    bottom: NDArray[np.float64] = array(
        block="griddata",
        dims=("nodes",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="bottom elevation for the one-dimensional cell",
    )
    idomain: Optional[NDArray[np.int64]] = array(
        block="griddata",
        dims=("nodes",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="idomain existence array",
    )
    __block_col_maps__: ClassVar[dict] = {
        "vertices": {
            "iv": "iv",
            "xv": "xv",
            "yv": "yv",
        },
        "cell2d": {
            "icell2d": "icell2d",
            "fdc": "fdc",
            "ncvert": "ncvert",
            "icvert": "icvert",
        },
    }

    def __attrs_post_init__(self):
        if self._vertices is not None:
            self._set_block(
                "vertices",
                "nvert",
                True,
                {
                    "iv": "iv",
                    "xv": "xv",
                    "yv": "yv",
                },
                self._vertices,
            )
        if self._cell2d is not None:
            self._set_block(
                "cell2d",
                "nodes",
                True,
                {
                    "icell2d": "icell2d",
                    "fdc": "fdc",
                    "ncvert": "ncvert",
                    "icvert": "icvert",
                },
                self._cell2d,
            )

    @property
    def vertices(self):
        return self._get_block(
            {
                "iv": "iv",
                "xv": "xv",
                "yv": "yv",
            }
        )

    @vertices.setter
    def vertices(self, value) -> None:
        self._set_block(
            "vertices",
            "nvert",
            True,
            {
                "iv": "iv",
                "xv": "xv",
                "yv": "yv",
            },
            value,
        )

    @property
    def cell2d(self):
        return self._get_block(
            {
                "icell2d": "icell2d",
                "fdc": "fdc",
                "ncvert": "ncvert",
                "icvert": "icvert",
            }
        )

    @cell2d.setter
    def cell2d(self, value) -> None:
        self._set_block(
            "cell2d",
            "nodes",
            True,
            {
                "icell2d": "icell2d",
                "fdc": "fdc",
                "ncvert": "ncvert",
                "icvert": "icvert",
            },
            value,
        )
