# autogenerated file, do not modify
# ruff: noqa: E501
from pathlib import Path
from typing import ClassVar, Optional

import attrs
from xattree import xattree

from flopy4.mf6.package import Package
from flopy4.mf6.record import Record
from flopy4.mf6.spec import field, path
from flopy4.utils import to_path


@xattree(kw_only=True)
class Oc(Package):
    @attrs.define
    class Qoutflowprint(Record):
        _keyword: ClassVar[str] = "qoutflow"
        _extra_tokens: ClassVar[tuple[str, ...]] = ("PRINT_FORMAT",)

    budget_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    budgetcsv_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    qoutflow_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    stage_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    qoutflowprint: Optional[Qoutflowprint] = field(block="options", default=None)
    # TODO: saverecord — complex type 'record' not yet supported
    # TODO: printrecord — complex type 'record' not yet supported
