# autogenerated file, do not modify
from typing import ClassVar, Optional

from pydantic import Field
from pydantic.dataclasses import dataclass

from flopy4.mf6._types import FloatArrayLike
from flopy4.mf6.package import CFG, Package
from flopy4.mf6.spec import field


@dataclass(config=CFG, kw_only=True)
class Cnd(Package):
    dfn_name: ClassVar[str] = "gwe-cnd"

    xt3d_off: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    xt3d_rhs: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    export_array_ascii: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    export_array_netcdf: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    alh: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
    )
    alv: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
    )
    ath1: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
    )
    ath2: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
    )
    atv: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
    )
    ktw: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
    )
    kts: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
    )
