# autogenerated file, do not modify
# ruff: noqa: E501
from pathlib import Path
from typing import ClassVar, Optional

import attrs
import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, dim, field, path
from flopy4.utils import to_path


@xattree(kw_only=True)
class Disu(Package):
    length_units: Optional[str] = field(
        block="options", default=None, longname="model length units"
    )
    nogrb: bool = field(block="options", default=False, longname="do not write binary grid file")
    grb_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    xorigin: Optional[float] = field(
        block="options",
        default=None,
        longname="x-position origin of the model grid coordinate system",
    )
    yorigin: Optional[float] = field(
        block="options",
        default=None,
        longname="y-position origin of the model grid coordinate system",
    )
    angrot: Optional[float] = field(block="options", default=None, longname="rotation angle")
    vertical_offset_tolerance: Optional[float] = field(
        block="options",
        default="0.0",
        longname="vertical length dimension for top and bottom checking",
    )
    export_array_ascii: bool = field(
        block="options", default=False, longname="export array variables to layered ascii files."
    )
    nodes: Optional[int] = dim(
        block="dimensions", coord=False, default=None, longname="number of layers"
    )
    nja: Optional[int] = dim(
        block="dimensions", coord=False, default=None, longname="number of columns"
    )
    nvert: Optional[int] = dim(
        block="dimensions", coord=False, default=None, longname="number of vertices"
    )
    _vertices: Optional[dict] = attrs.field(alias="vertices", default=None, repr=False)
    iv: Optional[NDArray[np.int64]] = array(
        block="vertices",
        dims=("nvert",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="vertex number",
        cellid=True,
    )
    xv: Optional[NDArray[np.float64]] = array(
        block="vertices",
        dims=("nvert",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="x-coordinate for vertex",
    )
    yv: Optional[NDArray[np.float64]] = array(
        block="vertices",
        dims=("nvert",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="y-coordinate for vertex",
    )
    _cell2d: Optional[dict] = attrs.field(alias="cell2d", default=None, repr=False)
    icell2d: Optional[NDArray[np.int64]] = array(
        block="cell2d",
        dims=("nodes",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="cell2d number",
        cellid=True,
    )
    xc: Optional[NDArray[np.float64]] = array(
        block="cell2d",
        dims=("nodes",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="x-coordinate for cell center",
    )
    yc: Optional[NDArray[np.float64]] = array(
        block="cell2d",
        dims=("nodes",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="y-coordinate for cell center",
    )
    ncvert: Optional[NDArray[np.int64]] = array(
        block="cell2d",
        dims=("nodes",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="number of cell vertices",
    )
    icvert: Optional[NDArray[np.int64]] = array(
        block="cell2d",
        dims=("nodes",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="array of vertex numbers",
        cellid=True,
    )
    top: NDArray[np.float64] = array(
        block="griddata",
        dims=("nodes",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="cell top elevation",
    )
    bot: NDArray[np.float64] = array(
        block="griddata",
        dims=("nodes",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="cell bottom elevation",
    )
    area: NDArray[np.float64] = array(
        block="griddata",
        dims=("nodes",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="cell surface area",
    )
    idomain: Optional[NDArray[np.int64]] = array(
        block="griddata",
        dims=("nodes",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="idomain existence array",
    )
    iac: NDArray[np.int64] = array(
        block="connectiondata",
        dims=("nodes",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="number of cell connections",
    )
    ja: NDArray[np.int64] = array(
        block="connectiondata",
        dims=("nja",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="grid connectivity",
    )
    ihc: NDArray[np.int64] = array(
        block="connectiondata",
        dims=("nja",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="connection type",
    )
    cl12: NDArray[np.float64] = array(
        block="connectiondata",
        dims=("nja",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="connection lengths",
    )
    hwva: NDArray[np.float64] = array(
        block="connectiondata",
        dims=("nja",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="connection lengths",
    )
    angldegx: Optional[NDArray[np.float64]] = array(
        block="connectiondata",
        dims=("nja",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="angle of face normal to connection",
    )
    __block_col_maps__: ClassVar[dict] = {
        "vertices": {
            "iv": "iv",
            "xv": "xv",
            "yv": "yv",
        },
        "cell2d": {
            "icell2d": "icell2d",
            "xc": "xc",
            "yc": "yc",
            "ncvert": "ncvert",
            "icvert": "icvert",
        },
    }

    def __attrs_post_init__(self):
        if self._vertices is not None:
            self._set_block(
                "vertices",
                "nvert",
                True,
                {
                    "iv": "iv",
                    "xv": "xv",
                    "yv": "yv",
                },
                self._vertices,
            )
        if self._cell2d is not None:
            self._set_block(
                "cell2d",
                "nodes",
                True,
                {
                    "icell2d": "icell2d",
                    "xc": "xc",
                    "yc": "yc",
                    "ncvert": "ncvert",
                    "icvert": "icvert",
                },
                self._cell2d,
            )

    @property
    def vertices(self):
        return self._get_block(
            {
                "iv": "iv",
                "xv": "xv",
                "yv": "yv",
            }
        )

    @vertices.setter
    def vertices(self, value) -> None:
        self._set_block(
            "vertices",
            "nvert",
            True,
            {
                "iv": "iv",
                "xv": "xv",
                "yv": "yv",
            },
            value,
        )

    @property
    def cell2d(self):
        return self._get_block(
            {
                "icell2d": "icell2d",
                "xc": "xc",
                "yc": "yc",
                "ncvert": "ncvert",
                "icvert": "icvert",
            }
        )

    @cell2d.setter
    def cell2d(self, value) -> None:
        self._set_block(
            "cell2d",
            "nodes",
            True,
            {
                "icell2d": "icell2d",
                "xc": "xc",
                "yc": "yc",
                "ncvert": "ncvert",
                "icvert": "icvert",
            },
            value,
        )
