# autogenerated file, do not modify
from typing import ClassVar, Optional

from pydantic import Field
from pydantic.dataclasses import dataclass

from flopy4.mf6._types import FloatArrayLike
from flopy4.mf6.package import CFG, Package
from flopy4.mf6.spec import field


@dataclass(config=CFG, kw_only=True)
class Est(Package):
    dfn_name: ClassVar[str] = "gwe-est"

    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    zero_order_decay_water: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    zero_order_decay_solid: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    density_water: Optional[float] = field(
        default=1000.0,
        block="options",
        optional=True,
    )
    heat_capacity_water: Optional[float] = field(
        default=4184.0,
        block="options",
        optional=True,
    )
    latent_heat_vaporization: Optional[float] = field(
        default=2453500.0,
        block="options",
        optional=True,
    )
    porosity: FloatArrayLike = field(
        default=None,
        block="griddata",
        shape=("nodes",),
    )
    decay_water: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        optional=True,
    )
    decay_solid: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        optional=True,
    )
    heat_capacity_solid: FloatArrayLike = field(
        default=None,
        block="griddata",
        shape=("nodes",),
    )
    density_solid: FloatArrayLike = field(
        default=None,
        block="griddata",
        shape=("nodes",),
    )
