# autogenerated file, do not modify
# ruff: noqa: E501
from pathlib import Path
from typing import ClassVar, Optional

import attrs
import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, dim, field, path
from flopy4.utils import to_path


@xattree(kw_only=True)
class Mwe(Package):
    multi_package: ClassVar[bool] = True

    flow_package_name: Optional[str] = field(
        block="options",
        default=None,
        longname="keyword to specify name of corresponding flow package",
    )
    auxiliary: Optional[list[str]] = array(
        block="options", default=None, longname="keyword to specify aux variables"
    )
    flow_package_auxiliary_name: Optional[str] = field(
        block="options",
        default=None,
        longname="keyword to specify name of temperature auxiliary variable in flow package",
    )
    boundnames: bool = field(block="options", default=False)
    print_input: bool = field(
        block="options", default=False, longname="print input to listing file"
    )
    print_temperature: bool = field(
        block="options", default=False, longname="print calculated temperatures to listing file"
    )
    print_flows: bool = field(
        block="options", default=False, longname="print calculated flows to listing file"
    )
    save_flows: bool = field(
        block="options", default=False, longname="save well flows to budget file"
    )
    temperature_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    budget_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    budgetcsv_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    ts_file: Optional[Path] = path(block="options", default=None, converter=to_path, inout="filein")
    obs_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="filein"
    )
    _packagedata: Optional[dict] = attrs.field(alias="packagedata", default=None, repr=False)
    npackagedata: Optional[int] = dim(block="__dim__", coord=False, default=None)
    naux: Optional[int] = dim(block="__dim__", coord=False, default=None)
    mawno: Optional[NDArray[np.int64]] = array(
        block="packagedata",
        dims=("npackagedata",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="well number for this entry",
        cellid=True,
    )
    strt: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("npackagedata",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="starting well temperature",
    )
    ktf: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("npackagedata",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="thermal conductivity of the feature",
    )
    fthk: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("npackagedata",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="thickness of the well feature",
    )
    aux: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("npackagedata", "naux"),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="auxiliary variables",
    )
    boundname: Optional[NDArray[np.object_]] = array(
        block="packagedata",
        dims=("npackagedata",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="well name",
    )
    # TODO: mwesetting — type 'union' not yet supported
    __block_col_maps__: ClassVar[dict] = {
        "packagedata": {
            "mawno": "mawno",
            "strt": "strt",
            "ktf": "ktf",
            "fthk": "fthk",
            "aux": "aux",
            "boundname": "boundname",
        },
    }

    def __attrs_post_init__(self):
        if self.auxiliary is not None:
            _aux = self.auxiliary
            self.naux = int(_aux.values.size) if hasattr(_aux, "values") else len(_aux)
        if self._packagedata is not None:
            self._set_block(
                "packagedata",
                "npackagedata",
                False,
                {
                    "mawno": "mawno",
                    "strt": "strt",
                    "ktf": "ktf",
                    "fthk": "fthk",
                    "aux": "aux",
                    "boundname": "boundname",
                },
                self._packagedata,
            )

    @property
    def packagedata(self):
        return self._get_block(
            {
                "mawno": "mawno",
                "strt": "strt",
                "ktf": "ktf",
                "fthk": "fthk",
                "aux": "aux",
                "boundname": "boundname",
            }
        )

    @packagedata.setter
    def packagedata(self, value) -> None:
        self._set_block(
            "packagedata",
            "npackagedata",
            False,
            {
                "mawno": "mawno",
                "strt": "strt",
                "ktf": "ktf",
                "fthk": "fthk",
                "aux": "aux",
                "boundname": "boundname",
            },
            value,
        )
