# autogenerated file, do not modify
# ruff: noqa: E501
from pathlib import Path
from typing import ClassVar, Optional

import attrs
import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, dim, field, path
from flopy4.utils import to_path


@xattree(kw_only=True)
class Obs(Package):
    multi_package: ClassVar[bool] = True

    digits: Optional[int] = field(block="options", default=None)
    print_input: bool = field(
        block="options", default=False, longname="print input to listing file"
    )
    _continuous: Optional[dict] = attrs.field(alias="continuous", default=None, repr=False)
    ncontinuous: Optional[int] = dim(block="__dim__", coord=False, default=None)
    obsname: Optional[NDArray[np.object_]] = array(
        block="continuous",
        dims=("ncontinuous",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="observation name",
    )
    obstype: Optional[NDArray[np.object_]] = array(
        block="continuous",
        dims=("ncontinuous",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="observation type",
    )
    id_: Optional[NDArray[np.object_]] = array(
        block="continuous",
        dims=("ncontinuous",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="time",
        cellid=True,
    )
    id2: Optional[NDArray[np.object_]] = array(
        block="continuous",
        dims=("ncontinuous",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="time",
        cellid=True,
    )
    output: Path = path(block="continuous", default=None, converter=to_path, inout="fileout")
    __block_col_maps__: ClassVar[dict] = {
        "continuous": {
            "obsname": "obsname",
            "obstype": "obstype",
            "id": "id_",
            "id2": "id2",
        },
    }

    def __attrs_post_init__(self):
        if self._continuous is not None:
            self._set_block(
                "continuous",
                "ncontinuous",
                False,
                {
                    "obsname": "obsname",
                    "obstype": "obstype",
                    "id": "id_",
                    "id2": "id2",
                },
                self._continuous,
            )

    @property
    def continuous(self):
        return self._get_block(
            {
                "obsname": "obsname",
                "obstype": "obstype",
                "id": "id_",
                "id2": "id2",
            }
        )

    @continuous.setter
    def continuous(self, value) -> None:
        self._set_block(
            "continuous",
            "ncontinuous",
            False,
            {
                "obsname": "obsname",
                "obstype": "obstype",
                "id": "id_",
                "id2": "id2",
            },
            value,
        )
