# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

from pydantic import Field
from pydantic.dataclasses import dataclass

from flopy4.mf6._types import FloatArrayLike, _optional_path
from flopy4.mf6.package import CFG, Package
from flopy4.mf6.spec import field, path


@dataclass(config=CFG, kw_only=True)
class Spca(Package):
    dfn_name: ClassVar[str] = "utl-spca"

    multi_package: ClassVar[bool] = True

    readasarrays: bool = field(
        default=True,
        block="options",
    )
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    tas_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="in",
    )
    concentration: Optional[FloatArrayLike] = field(
        default=None,
        block="period",
        reader="readarray",
        layered=False,
    )
    temperature: Optional[FloatArrayLike] = field(
        default=None,
        block="period",
        reader="readarray",
        layered=False,
    )
