# autogenerated file, do not modify
from typing import ClassVar, Optional

from pydantic import Field
from pydantic.dataclasses import dataclass

from flopy4.mf6.package import CFG, Package
from flopy4.mf6.record import Record
from flopy4.mf6.spec import field


@dataclass(config=CFG, kw_only=True)
class Tas(Package):
    dfn_name: ClassVar[str] = "utl-tas"

    multi_package: ClassVar[bool] = True

    @dataclass(config=CFG)
    class InterpolationMethod(Record):
        _keyword: ClassVar[str] = "method"
        interpolation_method: str = Field()

    # TODO: time_series_namerecord — type 'record' not yet supported
    interpolation_method: Optional[InterpolationMethod] = field(
        default=None,
        block="attributes",
    )
    # TODO: sfacrecord — type 'record' not yet supported
    # TODO: tas_array — unshaped (variadic-count) array not yet supported
