# autogenerated file, do not modify
# ruff: noqa: E501
from typing import ClassVar, Optional

import attrs
import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.record import Record
from flopy4.mf6.spec import array, dim, field


@xattree(kw_only=True)
class Ts(Package):
    multi_package: ClassVar[bool] = True

    @attrs.define
    class TimeSeriesName(Record):
        _keyword: ClassVar[str] = "names"
        time_series_names: str = attrs.field()

    @attrs.define
    class InterpolationMethod(Record):
        _keyword: ClassVar[str] = "methods"
        interpolation_method: str = attrs.field()

    @attrs.define
    class Sfac(Record):
        _keyword: ClassVar[str] = "sfacs"
        sfacval: float = attrs.field()

    @attrs.define
    class SfacrecordSingle(Record):
        _keyword: ClassVar[str] = ""
        sfacval: float = attrs.field()

    _timeseries: Optional[dict] = attrs.field(alias="timeseries", default=None, repr=False)
    ntimeseries: Optional[int] = dim(block="__dim__", coord=False, default=None)
    ts_time: Optional[NDArray[np.float64]] = array(
        block="timeseries",
        dims=("ntimeseries",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
    )
    ts_array: Optional[NDArray[np.float64]] = array(
        block="timeseries",
        dims=("ntimeseries",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
    )
    time_series_name: Optional[TimeSeriesName] = field(block="attributes", default=None)
    interpolation_method: Optional[InterpolationMethod] = field(block="attributes", default=None)
    # TODO: interpolation_methodrecord_single — complex type 'record' not yet supported
    method: bool = field(block="attributes", default=False)
    interpolation_method_single: str = field(block="attributes")
    sfac: Optional[Sfac] = field(block="attributes", default=None)
    sfacrecord_single: Optional[SfacrecordSingle] = field(block="attributes", default=None)
    __block_col_maps__: ClassVar[dict] = {
        "timeseries": {
            "ts_time": "ts_time",
            "ts_array": "ts_array",
        },
    }

    def __attrs_post_init__(self):
        if self._timeseries is not None:
            self._set_block(
                "timeseries",
                "ntimeseries",
                False,
                {
                    "ts_time": "ts_time",
                    "ts_array": "ts_array",
                },
                self._timeseries,
            )

    @property
    def timeseries(self):
        return self._get_block(
            {
                "ts_time": "ts_time",
                "ts_array": "ts_array",
            }
        )

    @timeseries.setter
    def timeseries(self, value) -> None:
        self._set_block(
            "timeseries",
            "ntimeseries",
            False,
            {
                "ts_time": "ts_time",
                "ts_array": "ts_array",
            },
            value,
        )
