# autogenerated file, do not modify
# ruff: noqa: E501
from pathlib import Path
from typing import ClassVar, Optional

import attrs
from xattree import xattree

from flopy4.mf6.package import Package
from flopy4.mf6.record import Record
from flopy4.mf6.spec import field, path
from flopy4.utils import to_path


@xattree(kw_only=True)
class Tvs(Package):
    @attrs.define
    class Tvssetting(Record):
        _keyword: ClassVar[str] = ""
        ss: float = attrs.field()
        sy: float = attrs.field()

    disable_storage_change_integration: bool = field(
        block="options", default=False, longname="deactivate storage change integration"
    )
    print_input: bool = field(
        block="options", default=False, longname="print input to listing file"
    )
    ts_file: Optional[Path] = path(block="options", default=None, converter=to_path, inout="filein")
    tvssetting: Optional[Tvssetting] = field(block="period", default=None)
