# autogenerated file, do not modify
# ruff: noqa: E501
from pathlib import Path
from typing import ClassVar, Optional

import attrs
import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, dim, field, path
from flopy4.utils import to_path


@xattree(kw_only=True)
class Chfgwf(Package):
    multi_package: ClassVar[bool] = True

    print_input: bool = field(
        block="options", default=False, longname="keyword to print input to list file"
    )
    print_flows: bool = field(
        block="options", default=False, longname="keyword to print chfgwf flows to list file"
    )
    fixed_conductance: bool = field(
        block="options", default=False, longname="keyword to indicate conductance is fixed"
    )
    obs_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="filein"
    )
    nexg: Optional[int] = dim(
        block="dimensions", coord=False, default=None, longname="number of exchanges"
    )
    _exchangedata: Optional[dict] = attrs.field(alias="exchangedata", default=None, repr=False)
    cellidm1: Optional[NDArray[np.int64]] = array(
        block="exchangedata",
        dims=("nexg",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="cellid of cell in surface water model",
        cellid=True,
    )
    cellidm2: Optional[NDArray[np.int64]] = array(
        block="exchangedata",
        dims=("nexg",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="cellid of cell in groundwater model",
        cellid=True,
    )
    bedleak: Optional[NDArray[np.float64]] = array(
        block="exchangedata",
        dims=("nexg",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="bed leakance",
    )
    cfact: Optional[NDArray[np.float64]] = array(
        block="exchangedata",
        dims=("nexg",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="factor used for conductance calculation",
    )
    __block_col_maps__: ClassVar[dict] = {
        "exchangedata": {
            "cellidm1": "cellidm1",
            "cellidm2": "cellidm2",
            "bedleak": "bedleak",
            "cfact": "cfact",
        },
    }

    def __attrs_post_init__(self):
        if self._exchangedata is not None:
            self._set_block(
                "exchangedata",
                "nexg",
                True,
                {
                    "cellidm1": "cellidm1",
                    "cellidm2": "cellidm2",
                    "bedleak": "bedleak",
                    "cfact": "cfact",
                },
                self._exchangedata,
            )

    @property
    def exchangedata(self):
        return self._get_block(
            {
                "cellidm1": "cellidm1",
                "cellidm2": "cellidm2",
                "bedleak": "bedleak",
                "cfact": "cfact",
            }
        )

    @exchangedata.setter
    def exchangedata(self, value) -> None:
        self._set_block(
            "exchangedata",
            "nexg",
            True,
            {
                "cellidm1": "cellidm1",
                "cellidm2": "cellidm2",
                "bedleak": "bedleak",
                "cfact": "cfact",
            },
            value,
        )
