# autogenerated file, do not modify
# ruff: noqa: E501
from pathlib import Path
from typing import ClassVar, Optional

import attrs
import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, dim, field, path
from flopy4.utils import to_path


@xattree(kw_only=True)
class Gwtgwt(Package):
    multi_package: ClassVar[bool] = True

    gwfmodelname1: str = field(
        block="options", longname="keyword to specify name of first corresponding GWF Model"
    )
    gwfmodelname2: str = field(
        block="options", longname="keyword to specify name of second corresponding GWF Model"
    )
    auxiliary: Optional[list[str]] = array(
        block="options", default=None, longname="keyword to specify aux variables"
    )
    boundnames: bool = field(block="options", default=False)
    print_input: bool = field(
        block="options", default=False, longname="keyword to print input to list file"
    )
    print_flows: bool = field(
        block="options", default=False, longname="keyword to print gwfgwf flows to list file"
    )
    save_flows: bool = field(
        block="options", default=False, longname="keyword to save GWFGWF flows"
    )
    adv_scheme: Optional[str] = field(block="options", default=None, longname="advective scheme")
    dsp_xt3d_off: bool = field(block="options", default=False, longname="deactivate xt3d")
    dsp_xt3d_rhs: bool = field(block="options", default=False, longname="xt3d on right-hand side")
    mvt_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="filein"
    )
    obs_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="filein"
    )
    dev_interfacemodel_on: bool = field(
        block="options", default=False, longname="activate interface model on exchange"
    )
    nexg: Optional[int] = dim(
        block="dimensions", coord=False, default=None, longname="number of exchanges"
    )
    _exchangedata: Optional[dict] = attrs.field(alias="exchangedata", default=None, repr=False)
    naux: Optional[int] = dim(block="__dim__", coord=False, default=None)
    cellidm1: Optional[NDArray[np.int64]] = array(
        block="exchangedata",
        dims=("nexg",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="cellid of first cell",
        cellid=True,
    )
    cellidm2: Optional[NDArray[np.int64]] = array(
        block="exchangedata",
        dims=("nexg",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="cellid of second cell",
        cellid=True,
    )
    ihc: Optional[NDArray[np.int64]] = array(
        block="exchangedata",
        dims=("nexg",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="integer flag for connection type",
    )
    cl1: Optional[NDArray[np.float64]] = array(
        block="exchangedata",
        dims=("nexg",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="connection distance",
    )
    cl2: Optional[NDArray[np.float64]] = array(
        block="exchangedata",
        dims=("nexg",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="connection distance",
    )
    hwva: Optional[NDArray[np.float64]] = array(
        block="exchangedata",
        dims=("nexg",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="horizontal cell width or area for vertical flow",
    )
    aux: Optional[NDArray[np.float64]] = array(
        block="exchangedata",
        dims=("nexg", "naux"),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="auxiliary variables",
    )
    boundname: Optional[NDArray[np.object_]] = array(
        block="exchangedata",
        dims=("nexg",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="exchange boundname",
    )
    __block_col_maps__: ClassVar[dict] = {
        "exchangedata": {
            "cellidm1": "cellidm1",
            "cellidm2": "cellidm2",
            "ihc": "ihc",
            "cl1": "cl1",
            "cl2": "cl2",
            "hwva": "hwva",
            "aux": "aux",
            "boundname": "boundname",
        },
    }

    def __attrs_post_init__(self):
        if self.auxiliary is not None:
            _aux = self.auxiliary
            self.naux = int(_aux.values.size) if hasattr(_aux, "values") else len(_aux)
        if self._exchangedata is not None:
            self._set_block(
                "exchangedata",
                "nexg",
                True,
                {
                    "cellidm1": "cellidm1",
                    "cellidm2": "cellidm2",
                    "ihc": "ihc",
                    "cl1": "cl1",
                    "cl2": "cl2",
                    "hwva": "hwva",
                    "aux": "aux",
                    "boundname": "boundname",
                },
                self._exchangedata,
            )

    @property
    def exchangedata(self):
        return self._get_block(
            {
                "cellidm1": "cellidm1",
                "cellidm2": "cellidm2",
                "ihc": "ihc",
                "cl1": "cl1",
                "cl2": "cl2",
                "hwva": "hwva",
                "aux": "aux",
                "boundname": "boundname",
            }
        )

    @exchangedata.setter
    def exchangedata(self, value) -> None:
        self._set_block(
            "exchangedata",
            "nexg",
            True,
            {
                "cellidm1": "cellidm1",
                "cellidm2": "cellidm2",
                "ihc": "ihc",
                "cl1": "cl1",
                "cl2": "cl2",
                "hwva": "hwva",
                "aux": "aux",
                "boundname": "boundname",
            },
            value,
        )
