# autogenerated file, do not modify
# ruff: noqa: E501
from pathlib import Path
from typing import ClassVar, Optional

import attrs
import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, dim, field, path
from flopy4.utils import to_path


@xattree(kw_only=True)
class Nam(Package):
    continue_: bool = field(block="options", default=False, longname="continue if not converged")
    nocheck: bool = field(block="options", default=False, longname="turn off checking")
    memory_print_option: Optional[str] = field(
        block="options", default=None, longname="memory print option"
    )
    profile_option: Optional[str] = field(
        block="options", default=None, longname="profiling option"
    )
    maxerrors: Optional[int] = field(
        block="options", default=None, longname="maximum number of errors"
    )
    print_input: bool = field(
        block="options", default=False, longname="print input to listing file"
    )
    hpc_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="filein"
    )
    _models: Optional[dict] = attrs.field(alias="models", default=None, repr=False)
    nmodels: Optional[int] = dim(block="__dim__", coord=False, default=None)
    mtype: Optional[NDArray[np.object_]] = array(
        block="models",
        dims=("nmodels",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="model type",
    )
    mfname: Optional[NDArray[np.object_]] = array(
        block="models",
        dims=("nmodels",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="file name for model name file",
    )
    mname: Optional[NDArray[np.object_]] = array(
        block="models",
        dims=("nmodels",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="name of model",
    )
    _exchanges: Optional[dict] = attrs.field(alias="exchanges", default=None, repr=False)
    nexchanges: Optional[int] = dim(block="__dim__", coord=False, default=None)
    exgtype: Optional[NDArray[np.object_]] = array(
        block="exchanges",
        dims=("nexchanges",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="exchange type",
    )
    exgfile: Optional[NDArray[np.object_]] = array(
        block="exchanges",
        dims=("nexchanges",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="input file for exchange",
    )
    exgmnamea: Optional[NDArray[np.object_]] = array(
        block="exchanges",
        dims=("nexchanges",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="name of model A",
    )
    exgmnameb: Optional[NDArray[np.object_]] = array(
        block="exchanges",
        dims=("nexchanges",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="name of model B",
    )
    _solutiongroup: Optional[dict] = attrs.field(alias="solutiongroup", default=None, repr=False)
    nsolutiongroup: Optional[int] = dim(block="__dim__", coord=False, default=None)
    slntype: Optional[NDArray[np.object_]] = array(
        block="solutiongroup",
        dims=("nsolutiongroup",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="type of solution",
    )
    slnfname: Optional[NDArray[np.object_]] = array(
        block="solutiongroup",
        dims=("nsolutiongroup",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="file name for solution input",
    )
    slnmnames: Optional[NDArray[np.object_]] = array(
        block="solutiongroup",
        dims=("nsolutiongroup",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="array of model names in this solution",
    )
    tdis6: str = field(block="timing", longname="name of tdis input file")
    mxiter: Optional[int] = field(
        block="solutiongroup", default=None, longname="maximum solution group iterations"
    )
    __block_col_maps__: ClassVar[dict] = {
        "models": {
            "mtype": "mtype",
            "mfname": "mfname",
            "mname": "mname",
        },
        "exchanges": {
            "exgtype": "exgtype",
            "exgfile": "exgfile",
            "exgmnamea": "exgmnamea",
            "exgmnameb": "exgmnameb",
        },
        "solutiongroup": {
            "slntype": "slntype",
            "slnfname": "slnfname",
            "slnmnames": "slnmnames",
        },
    }

    def __attrs_post_init__(self):
        if self._models is not None:
            self._set_block(
                "models",
                "nmodels",
                False,
                {
                    "mtype": "mtype",
                    "mfname": "mfname",
                    "mname": "mname",
                },
                self._models,
            )
        if self._exchanges is not None:
            self._set_block(
                "exchanges",
                "nexchanges",
                False,
                {
                    "exgtype": "exgtype",
                    "exgfile": "exgfile",
                    "exgmnamea": "exgmnamea",
                    "exgmnameb": "exgmnameb",
                },
                self._exchanges,
            )
        if self._solutiongroup is not None:
            self._set_block(
                "solutiongroup",
                "nsolutiongroup",
                False,
                {
                    "slntype": "slntype",
                    "slnfname": "slnfname",
                    "slnmnames": "slnmnames",
                },
                self._solutiongroup,
            )

    @property
    def models(self):
        return self._get_block(
            {
                "mtype": "mtype",
                "mfname": "mfname",
                "mname": "mname",
            }
        )

    @models.setter
    def models(self, value) -> None:
        self._set_block(
            "models",
            "nmodels",
            False,
            {
                "mtype": "mtype",
                "mfname": "mfname",
                "mname": "mname",
            },
            value,
        )

    @property
    def exchanges(self):
        return self._get_block(
            {
                "exgtype": "exgtype",
                "exgfile": "exgfile",
                "exgmnamea": "exgmnamea",
                "exgmnameb": "exgmnameb",
            }
        )

    @exchanges.setter
    def exchanges(self, value) -> None:
        self._set_block(
            "exchanges",
            "nexchanges",
            False,
            {
                "exgtype": "exgtype",
                "exgfile": "exgfile",
                "exgmnamea": "exgmnamea",
                "exgmnameb": "exgmnameb",
            },
            value,
        )

    @property
    def solutiongroup(self):
        return self._get_block(
            {
                "slntype": "slntype",
                "slnfname": "slnfname",
                "slnmnames": "slnmnames",
            }
        )

    @solutiongroup.setter
    def solutiongroup(self, value) -> None:
        self._set_block(
            "solutiongroup",
            "nsolutiongroup",
            False,
            {
                "slntype": "slntype",
                "slnfname": "slnfname",
                "slnmnames": "slnmnames",
            },
            value,
        )
