# autogenerated file, do not modify
# ruff: noqa: E501
from pathlib import Path
from typing import Optional

import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, field, path
from flopy4.utils import to_path


@xattree(kw_only=True)
class Dfw(Package):
    central_in_space: bool = field(
        block="options", default=False, longname="use central in space weighting"
    )
    length_conversion: Optional[float] = field(
        block="options", default=None, longname="length conversion factor"
    )
    time_conversion: Optional[float] = field(
        block="options", default=None, longname="time conversion factor"
    )
    save_flows: bool = field(block="options", default=False, longname="keyword to save DFW flows")
    print_flows: bool = field(
        block="options", default=False, longname="keyword to print DFW flows to listing file"
    )
    save_velocity: bool = field(block="options", default=False, longname="keyword to save velocity")
    obs_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="filein"
    )
    export_array_ascii: bool = field(
        block="options", default=False, longname="export array variables to layered ascii files."
    )
    dev_swr_conductance: bool = field(
        block="options", default=False, longname="use SWR conductance formulation"
    )
    manningsn: NDArray[np.float64] = array(
        block="griddata",
        dims=("nodes",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="mannings roughness coefficient",
    )
    idcxs: Optional[NDArray[np.int64]] = array(
        block="griddata",
        dims=("nodes",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="cross section number",
    )
