# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional, Union

from pydantic import Field, SkipValidation
from pydantic.dataclasses import dataclass

from flopy4.mf6._types import _optional_path
from flopy4.mf6.item import Item
from flopy4.mf6.package import CFG, Package
from flopy4.mf6.spec import field, path


@dataclass(config=CFG, kw_only=True)
class Buy(Package):
    dfn_name: ClassVar[str] = "gwf-buy"

    @dataclass(config=CFG)
    class Packagedata(Item):
        irhospec: int = field(index=True, pk=True)
        drhodc: float = field()
        crhoref: float = field()
        modelname: Union[float, str] = field()
        auxspeciesname: Union[float, str] = field()
        aux: tuple = ()

    hhformulation_rhs: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    denseref: Optional[float] = field(
        default=1000.0,
        block="options",
        optional=True,
    )
    density_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
    )
    nrhospecies: Optional[int] = field(
        default=None,
        block="dimensions",
    )
    packagedata: Optional[SkipValidation[list[Packagedata]]] = field(
        default=None,
        block="packagedata",
        auto_from="packagedata",
    )

BuyPackagedata = Buy.Packagedata
