# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

from pydantic.dataclasses import dataclass

from flopy4.mf6._types import FloatArrayLike, _optional_path
from flopy4.mf6.package import CFG, Package
from flopy4.mf6.spec import field, path


@dataclass(config=CFG, kw_only=True)
class Ghbg(Package):
    dfn_name: ClassVar[str] = "gwf-ghbg"

    multi_package: ClassVar[bool] = True

    readarraygrid: bool = field(
        default=True,
        block="options",
    )
    auxiliary: Optional[list[str]] = field(
        default=None,
        block="options",
        optional=True,
    )
    auxmultname: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
    )
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    print_flows: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    obs_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="in",
    )
    mover: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    export_array_netcdf: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    bhead: Optional[FloatArrayLike] = field(
        default=None,
        block="period",
        reader="readarray",
        layered=True,
    )
    cond: Optional[FloatArrayLike] = field(
        default=None,
        block="period",
        reader="readarray",
        layered=True,
    )
    aux: Optional[FloatArrayLike] = field(
        default=None,
        block="period",
        reader="readarray",
        layered=True,
    )
