# autogenerated file, do not modify
# ruff: noqa: E501
from typing import ClassVar, Optional

import attrs
import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, dim, field


@xattree(kw_only=True)
class Gnc(Package):
    print_input: bool = field(
        block="options", default=False, longname="print input to listing file"
    )
    print_flows: bool = field(
        block="options", default=False, longname="print simulated flows to listing file"
    )
    explicit: bool = field(block="options", default=False, longname="use explicit GNC formulation")
    numgnc: Optional[int] = dim(
        block="dimensions", coord=False, default=None, longname="number of ghost node corrections"
    )
    numalphaj: Optional[int] = dim(
        block="dimensions", coord=False, default=None, longname="number of contributing factors"
    )
    _gncdata: Optional[dict] = attrs.field(alias="gncdata", default=None, repr=False)
    cellidn: Optional[NDArray[np.int64]] = array(
        block="gncdata",
        dims=("numgnc",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="GNC cellid n",
        cellid=True,
    )
    cellidm: Optional[NDArray[np.int64]] = array(
        block="gncdata",
        dims=("numgnc",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="GNC cellid n",
        cellid=True,
    )
    cellidsj: Optional[NDArray[np.int64]] = array(
        block="gncdata",
        dims=("numgnc",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="GNC contributing cells",
        cellid=True,
    )
    alphasj: Optional[NDArray[np.float64]] = array(
        block="gncdata",
        dims=("numgnc",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="GNC contributing factors",
    )
    __block_col_maps__: ClassVar[dict] = {
        "gncdata": {
            "cellidn": "cellidn",
            "cellidm": "cellidm",
            "cellidsj": "cellidsj",
            "alphasj": "alphasj",
        },
    }

    def __attrs_post_init__(self):
        if self._gncdata is not None:
            self._set_block(
                "gncdata",
                "numgnc",
                True,
                {
                    "cellidn": "cellidn",
                    "cellidm": "cellidm",
                    "cellidsj": "cellidsj",
                    "alphasj": "alphasj",
                },
                self._gncdata,
            )

    @property
    def gncdata(self):
        return self._get_block(
            {
                "cellidn": "cellidn",
                "cellidm": "cellidm",
                "cellidsj": "cellidsj",
                "alphasj": "alphasj",
            }
        )

    @gncdata.setter
    def gncdata(self, value) -> None:
        self._set_block(
            "gncdata",
            "numgnc",
            True,
            {
                "cellidn": "cellidn",
                "cellidm": "cellidm",
                "cellidsj": "cellidsj",
                "alphasj": "alphasj",
            },
            value,
        )
