# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional, Union

from pydantic import Field, SkipValidation
from pydantic.dataclasses import dataclass

from flopy4.mf6._types import _optional_path
from flopy4.mf6.item import Item
from flopy4.mf6.package import CFG, Package
from flopy4.mf6.spec import field, path


@dataclass(config=CFG, kw_only=True)
class Lak(Package):
    dfn_name: ClassVar[str] = "gwf-lak"

    multi_package: ClassVar[bool] = True

    @dataclass(config=CFG)
    class Packagedata(Item):
        ifno: int = field(index=True, pk=True)
        strt: float = field()
        nlakeconn: int = field()
        aux: tuple = ()
        boundname: Optional[str] = field(default=None, optional=True)

    @dataclass(config=CFG)
    class Connectiondata(Item):
        ifno: int = field(index=True, fk="packagedata.ifno")
        iconn: int = field(index=True)
        cellid: tuple = field(cellid=True)
        claktype: Union[float, str] = field()
        bedleak: Union[float, str] = field()
        belev: float = field()
        telev: float = field()
        connlen: float = field()
        connwidth: float = field()

    @dataclass(config=CFG)
    class Tables(Item):
        ifno: int = field(index=True, fk="packagedata.ifno")
        tab6_filename: Path = path(converter=Path, direction="in", prefix=("TAB6",))

    @dataclass(config=CFG)
    class Outlets(Item):
        outletno: int = field(index=True, pk=True)
        lakein: int = field(index=True, fk="packagedata.ifno")
        lakeout: int = field(index=True, fk="packagedata.ifno")
        couttype: Union[float, str] = field()
        invert: Union[float, str] = field(time_series=True)
        width: Union[float, str] = field(time_series=True)
        rough: Union[float, str] = field(time_series=True)
        slope: Union[float, str] = field(time_series=True)

    @dataclass(config=CFG)
    class Status(Item):
        _keyword: ClassVar[str] = "status"
        lakeno: int = field(index=True, fk="packagedata.ifno")
        status: Union[float, str] = field()

    @dataclass(config=CFG)
    class Stage(Item):
        _keyword: ClassVar[str] = "stage"
        lakeno: int = field(index=True, fk="packagedata.ifno")
        stage: Union[float, str] = field(time_series=True)

    @dataclass(config=CFG)
    class Rainfall(Item):
        _keyword: ClassVar[str] = "rainfall"
        lakeno: int = field(index=True, fk="packagedata.ifno")
        rainfall: Union[float, str] = field(time_series=True)

    @dataclass(config=CFG)
    class Evaporation(Item):
        _keyword: ClassVar[str] = "evaporation"
        lakeno: int = field(index=True, fk="packagedata.ifno")
        evaporation: Union[float, str] = field(time_series=True)

    @dataclass(config=CFG)
    class Runoff(Item):
        _keyword: ClassVar[str] = "runoff"
        lakeno: int = field(index=True, fk="packagedata.ifno")
        runoff: Union[float, str] = field(time_series=True)

    @dataclass(config=CFG)
    class Inflow(Item):
        _keyword: ClassVar[str] = "inflow"
        lakeno: int = field(index=True, fk="packagedata.ifno")
        inflow: Union[float, str] = field(time_series=True)

    @dataclass(config=CFG)
    class Withdrawal(Item):
        _keyword: ClassVar[str] = "withdrawal"
        lakeno: int = field(index=True, fk="packagedata.ifno")
        withdrawal: Union[float, str] = field(time_series=True)

    @dataclass(config=CFG)
    class Rate(Item):
        _keyword: ClassVar[str] = "rate"
        outletno: int = field(index=True, fk="outlets.outletno")
        rate: Union[float, str] = field(time_series=True)

    @dataclass(config=CFG)
    class Invert(Item):
        _keyword: ClassVar[str] = "invert"
        outletno: int = field(index=True, fk="outlets.outletno")
        invert: Union[float, str] = field(time_series=True)

    @dataclass(config=CFG)
    class Width(Item):
        _keyword: ClassVar[str] = "width"
        outletno: int = field(index=True, fk="outlets.outletno")
        width: Union[float, str] = field(time_series=True)

    @dataclass(config=CFG)
    class Slope(Item):
        _keyword: ClassVar[str] = "slope"
        outletno: int = field(index=True, fk="outlets.outletno")
        slope: Union[float, str] = field(time_series=True)

    @dataclass(config=CFG)
    class Rough(Item):
        _keyword: ClassVar[str] = "rough"
        outletno: int = field(index=True, fk="outlets.outletno")
        rough: Union[float, str] = field(time_series=True)

    @dataclass(config=CFG)
    class Auxiliary(Item):
        _keyword: ClassVar[str] = "auxiliary"
        lakeno: int = field(index=True, fk="packagedata.ifno")
        auxname: Union[float, str] = field()
        auxval: Union[float, str] = field(time_series=True)

    _StressPeriodDataItem = (
        Status |
        Stage |
        Rainfall |
        Evaporation |
        Runoff |
        Inflow |
        Withdrawal |
        Rate |
        Invert |
        Width |
        Slope |
        Rough |
        Auxiliary
    )

    auxiliary: Optional[list[str]] = field(
        default=None,
        block="options",
        optional=True,
    )
    boundnames: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    print_stage: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    print_flows: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    stage_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
    )
    budget_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
    )
    budgetcsv_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
    )
    package_convergence_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
    )
    ts_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="in",
    )
    obs_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="in",
    )
    mover: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    surfdep: Optional[float] = field(
        default=None,
        block="options",
        optional=True,
    )
    implicit: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    maximum_iterations: Optional[int] = field(
        default=None,
        block="options",
        optional=True,
    )
    maximum_stage_change: Optional[float] = field(
        default=None,
        block="options",
        optional=True,
    )
    time_conversion: Optional[float] = field(
        default=None,
        block="options",
        optional=True,
    )
    length_conversion: Optional[float] = field(
        default=None,
        block="options",
        optional=True,
    )
    nlakes: Optional[int] = field(
        default=None,
        block="dimensions",
    )
    noutlets: Optional[int] = field(
        default=None,
        block="dimensions",
    )
    ntables: Optional[int] = field(
        default=None,
        block="dimensions",
    )
    packagedata: Optional[SkipValidation[list[Packagedata]]] = field(
        default=None,
        block="packagedata",
        auto_from="packagedata",
    )
    connectiondata: Optional[SkipValidation[list[Connectiondata]]] = field(
        default=None,
        block="connectiondata",
        write_if_empty=True,
    )
    tables: Optional[SkipValidation[list[Tables]]] = field(
        default=None,
        block="tables",
        auto_from="tables",
    )
    outlets: Optional[SkipValidation[list[Outlets]]] = field(
        default=None,
        block="outlets",
        auto_from="outlets",
    )
    _stress_period_data: Optional[SkipValidation[dict[int, list[_StressPeriodDataItem]]]] = field(
        alias="stress_period_data",
        default=None,
        repr=False,
        block="period",
        fill_forward=True,
    )

LakPackagedata = Lak.Packagedata
LakConnectiondata = Lak.Connectiondata
LakTables = Lak.Tables
LakOutlets = Lak.Outlets
LakStatus = Lak.Status
LakStage = Lak.Stage
LakRainfall = Lak.Rainfall
LakEvaporation = Lak.Evaporation
LakRunoff = Lak.Runoff
LakInflow = Lak.Inflow
LakWithdrawal = Lak.Withdrawal
LakRate = Lak.Rate
LakInvert = Lak.Invert
LakWidth = Lak.Width
LakSlope = Lak.Slope
LakRough = Lak.Rough
LakAuxiliary = Lak.Auxiliary
