# autogenerated file, do not modify
# ruff: noqa: E501
from pathlib import Path
from typing import ClassVar, Optional

import attrs
import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, dim, field, path
from flopy4.utils import to_path


@xattree(kw_only=True)
class Maw(Package):
    multi_package: ClassVar[bool] = True

    auxiliary: Optional[list[str]] = array(
        block="options", default=None, longname="keyword to specify aux variables"
    )
    boundnames: bool = field(block="options", default=False)
    print_input: bool = field(
        block="options", default=False, longname="print input to listing file"
    )
    print_head: bool = field(
        block="options", default=False, longname="print calculated heads to listing file"
    )
    print_flows: bool = field(
        block="options", default=False, longname="print calculated flows to listing file"
    )
    save_flows: bool = field(
        block="options", default=False, longname="save well flows to budget file"
    )
    head_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    budget_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    budgetcsv_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    no_well_storage: bool = field(
        block="options", default=False, longname="deactivate well storage"
    )
    flow_correction: bool = field(
        block="options", default=False, longname="activate flow correction"
    )
    flowing_wells: bool = field(block="options", default=False, longname="activate flowing wells")
    shutdown_theta: Optional[float] = field(
        block="options", default=None, longname="shutdown theta"
    )
    shutdown_kappa: Optional[float] = field(
        block="options", default=None, longname="shutdown kappa"
    )
    mfrcsv_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    ts_file: Optional[Path] = path(block="options", default=None, converter=to_path, inout="filein")
    obs_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="filein"
    )
    mover: bool = field(block="options", default=False)
    nmawwells: Optional[int] = dim(
        block="dimensions", coord=False, default=None, longname="number of MAW wells"
    )
    _packagedata: Optional[dict] = attrs.field(alias="packagedata", default=None, repr=False)
    naux: Optional[int] = dim(block="__dim__", coord=False, default=None)
    packagedata_ifno: Optional[NDArray[np.int64]] = array(
        block="packagedata",
        dims=("nmawwells",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="well number for this entry",
        cellid=True,
    )
    radius: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("nmawwells",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="well radius",
    )
    bottom: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("nmawwells",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="well bottom",
    )
    strt: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("nmawwells",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="starting head",
    )
    condeqn: Optional[NDArray[np.object_]] = array(
        block="packagedata",
        dims=("nmawwells",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="conductance equation",
    )
    ngwfnodes: Optional[NDArray[np.int64]] = array(
        block="packagedata",
        dims=("nmawwells",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="number of connected GWF cells",
    )
    aux: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("nmawwells", "naux"),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="auxiliary variables",
    )
    boundname: Optional[NDArray[np.object_]] = array(
        block="packagedata",
        dims=("nmawwells",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="well name",
    )
    _connectiondata: Optional[dict] = attrs.field(alias="connectiondata", default=None, repr=False)
    connectiondata_ifno: Optional[NDArray[np.int64]] = array(
        block="connectiondata",
        dims=("nmawwells",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="well number for this entry",
        cellid=True,
    )
    icon: Optional[NDArray[np.int64]] = array(
        block="connectiondata",
        dims=("nmawwells",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="connection number",
        cellid=True,
    )
    cellid: Optional[NDArray[np.object_]] = array(
        block="connectiondata",
        dims=("nmawwells",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="cell identifier",
        cellid=True,
    )
    scrn_top: Optional[NDArray[np.float64]] = array(
        block="connectiondata",
        dims=("nmawwells",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="screen top",
    )
    scrn_bot: Optional[NDArray[np.float64]] = array(
        block="connectiondata",
        dims=("nmawwells",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="screen bottom",
    )
    hk_skin: Optional[NDArray[np.float64]] = array(
        block="connectiondata",
        dims=("nmawwells",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="skin data",
    )
    radius_skin: Optional[NDArray[np.float64]] = array(
        block="connectiondata",
        dims=("nmawwells",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="skin radius",
    )
    ifno: Optional[NDArray[np.int64]] = array(
        block="period",
        dims=("nper",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="well number for this entry",
    )
    # TODO: mawsetting — type 'union' not yet supported
    __block_col_maps__: ClassVar[dict] = {
        "packagedata": {
            "ifno": "packagedata_ifno",
            "radius": "radius",
            "bottom": "bottom",
            "strt": "strt",
            "condeqn": "condeqn",
            "ngwfnodes": "ngwfnodes",
            "aux": "aux",
            "boundname": "boundname",
        },
        "connectiondata": {
            "ifno": "connectiondata_ifno",
            "icon": "icon",
            "cellid": "cellid",
            "scrn_top": "scrn_top",
            "scrn_bot": "scrn_bot",
            "hk_skin": "hk_skin",
            "radius_skin": "radius_skin",
        },
    }

    def __attrs_post_init__(self):
        if self.auxiliary is not None:
            _aux = self.auxiliary
            self.naux = int(_aux.values.size) if hasattr(_aux, "values") else len(_aux)
        if self._packagedata is not None:
            self._set_block(
                "packagedata",
                "nmawwells",
                True,
                {
                    "ifno": "packagedata_ifno",
                    "radius": "radius",
                    "bottom": "bottom",
                    "strt": "strt",
                    "condeqn": "condeqn",
                    "ngwfnodes": "ngwfnodes",
                    "aux": "aux",
                    "boundname": "boundname",
                },
                self._packagedata,
            )
        if self._connectiondata is not None:
            self._set_block(
                "connectiondata",
                "nmawwells",
                True,
                {
                    "ifno": "connectiondata_ifno",
                    "icon": "icon",
                    "cellid": "cellid",
                    "scrn_top": "scrn_top",
                    "scrn_bot": "scrn_bot",
                    "hk_skin": "hk_skin",
                    "radius_skin": "radius_skin",
                },
                self._connectiondata,
            )

    @property
    def packagedata(self):
        return self._get_block(
            {
                "ifno": "packagedata_ifno",
                "radius": "radius",
                "bottom": "bottom",
                "strt": "strt",
                "condeqn": "condeqn",
                "ngwfnodes": "ngwfnodes",
                "aux": "aux",
                "boundname": "boundname",
            }
        )

    @packagedata.setter
    def packagedata(self, value) -> None:
        self._set_block(
            "packagedata",
            "nmawwells",
            True,
            {
                "ifno": "packagedata_ifno",
                "radius": "radius",
                "bottom": "bottom",
                "strt": "strt",
                "condeqn": "condeqn",
                "ngwfnodes": "ngwfnodes",
                "aux": "aux",
                "boundname": "boundname",
            },
            value,
        )

    @property
    def connectiondata(self):
        return self._get_block(
            {
                "ifno": "connectiondata_ifno",
                "icon": "icon",
                "cellid": "cellid",
                "scrn_top": "scrn_top",
                "scrn_bot": "scrn_bot",
                "hk_skin": "hk_skin",
                "radius_skin": "radius_skin",
            }
        )

    @connectiondata.setter
    def connectiondata(self, value) -> None:
        self._set_block(
            "connectiondata",
            "nmawwells",
            True,
            {
                "ifno": "connectiondata_ifno",
                "icon": "icon",
                "cellid": "cellid",
                "scrn_top": "scrn_top",
                "scrn_bot": "scrn_bot",
                "hk_skin": "hk_skin",
                "radius_skin": "radius_skin",
            },
            value,
        )
