# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

from pydantic import Field
from pydantic.dataclasses import dataclass

from flopy4.mf6._types import FloatArrayLike, IntArrayLike, _optional_path
from flopy4.mf6.package import CFG, Package
from flopy4.mf6.record import Record
from flopy4.mf6.spec import field, path


@dataclass(config=CFG, kw_only=True)
class Npf(Package):
    dfn_name: ClassVar[str] = "gwf-npf"

    @dataclass(config=CFG)
    class Cvoptions(Record):
        _keyword: ClassVar[str] = "variablecv"
        dewatered: Optional[bool] = Field(default=None, json_schema_extra={"tagged": True})

    @dataclass(config=CFG)
    class Rewet(Record):
        _keyword: ClassVar[str] = "rewet"
        wetfct: float = Field(json_schema_extra={"tagged": True})
        iwetit: int = Field(json_schema_extra={"tagged": True})
        ihdwet: int = Field(json_schema_extra={"tagged": True})

    @dataclass(config=CFG)
    class Xt3doptions(Record):
        _keyword: ClassVar[str] = "xt3d"
        rhs: Optional[bool] = Field(default=None, json_schema_extra={"tagged": True})

    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    print_flows: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    alternative_cell_averaging: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
    )
    thickstrt: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    cvoptions: Optional[Cvoptions] = field(
        default=None,
        block="options",
    )
    perched: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    rewet: Optional[Rewet] = field(
        default=None,
        block="options",
    )
    xt3doptions: Optional[Xt3doptions] = field(
        default=None,
        block="options",
    )
    highest_cell_saturation: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    save_specific_discharge: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    save_saturation: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    k22overk: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    k33overk: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    tvk_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="in",
    )
    export_array_ascii: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    export_array_netcdf: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    icelltype: Optional[IntArrayLike] = field(
        default=0,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
    )  # type: ignore[assignment]
    k: Optional[FloatArrayLike] = field(
        default=1.0,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
    )  # type: ignore[assignment]
    k22: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
    )
    k33: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
    )
    angle1: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
    )
    angle2: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
    )
    angle3: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
    )
    wetdry: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
    )
