# autogenerated file, do not modify
# ruff: noqa: E501
from pathlib import Path
from typing import ClassVar, Optional

import attrs
import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, dim, field, path
from flopy4.utils import to_path


@xattree(kw_only=True)
class Sfr(Package):
    multi_package: ClassVar[bool] = True

    storage: bool = field(block="options", default=False, longname="activate reach storage")
    auxiliary: Optional[list[str]] = array(
        block="options", default=None, longname="keyword to specify aux variables"
    )
    boundnames: bool = field(block="options", default=False)
    print_input: bool = field(
        block="options", default=False, longname="print input to listing file"
    )
    print_stage: bool = field(
        block="options", default=False, longname="print calculated stages to listing file"
    )
    print_flows: bool = field(
        block="options", default=False, longname="print calculated flows to listing file"
    )
    save_flows: bool = field(
        block="options", default=False, longname="save stream reach flows to budget file"
    )
    stage_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    budget_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    budgetcsv_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    package_convergence_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    ts_file: Optional[Path] = path(block="options", default=None, converter=to_path, inout="filein")
    obs_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="filein"
    )
    mover: bool = field(block="options", default=False)
    maximum_picard_iterations: Optional[int] = field(
        block="options", default=None, longname="SFR picard iterations"
    )
    maximum_iterations: Optional[int] = field(
        block="options", default=None, longname="SFR Newton-Raphson iterations"
    )
    maximum_depth_change: Optional[float] = field(
        block="options", default=None, longname="depth closure tolerance"
    )
    unit_conversion: Optional[float] = field(
        block="options", default=None, longname="conversion factor"
    )
    length_conversion: Optional[float] = field(
        block="options", default=None, longname="length conversion factor"
    )
    time_conversion: Optional[float] = field(
        block="options", default=None, longname="time conversion factor"
    )
    dev_storage_weight: Optional[float] = field(
        block="options", default=None, longname="reach storage time weighting"
    )
    nreaches: Optional[int] = dim(
        block="dimensions", coord=False, default=None, longname="maximum number reaches"
    )
    _packagedata: Optional[dict] = attrs.field(alias="packagedata", default=None, repr=False)
    naux: Optional[int] = dim(block="__dim__", coord=False, default=None)
    packagedata_ifno: Optional[NDArray[np.int64]] = array(
        block="packagedata",
        dims=("nreaches",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="reach number for this entry",
        cellid=True,
    )
    cellid: Optional[NDArray[np.object_]] = array(
        block="packagedata",
        dims=("nreaches",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="cell identifier",
        cellid=True,
    )
    rlen: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("nreaches",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="reach length",
    )
    rwid: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("nreaches",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="reach width",
    )
    rgrd: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("nreaches",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="stream gradient",
    )
    rtp: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("nreaches",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="reach streambed top elevation",
    )
    rbth: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("nreaches",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="streambed thickness",
    )
    rhk: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("nreaches",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="reach bed hydraulic conductivity",
    )
    man: Optional[NDArray[np.object_]] = array(
        block="packagedata",
        dims=("nreaches",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="Manning's roughness coefficient",
    )
    ncon: Optional[NDArray[np.int64]] = array(
        block="packagedata",
        dims=("nreaches",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="number of connected reaches",
    )
    ustrf: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("nreaches",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="fraction of upstream flow",
    )
    ndv: Optional[NDArray[np.int64]] = array(
        block="packagedata",
        dims=("nreaches",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="number of downstream reaches",
    )
    aux: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("nreaches", "naux"),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="auxiliary variables",
    )
    boundname: Optional[NDArray[np.object_]] = array(
        block="packagedata",
        dims=("nreaches",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="well name",
    )
    _crosssections: Optional[dict] = attrs.field(alias="crosssections", default=None, repr=False)
    crosssections_ifno: Optional[NDArray[np.int64]] = array(
        block="crosssections",
        dims=("nreaches",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="reach number for this entry",
        cellid=True,
    )
    tab6_filename: Optional[NDArray[np.object_]] = array(
        block="crosssections",
        dims=("nreaches",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="table file name",
        prefix=("TAB6", "FILEIN"),
    )
    _connectiondata: Optional[dict] = attrs.field(alias="connectiondata", default=None, repr=False)
    connectiondata_ifno: Optional[NDArray[np.int64]] = array(
        block="connectiondata",
        dims=("nreaches",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="reach number for this entry",
        cellid=True,
    )
    ic: Optional[NDArray[np.int64]] = array(
        block="connectiondata",
        dims=("nreaches",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="connected reach numbers",
        cellid=True,
    )
    _diversions: Optional[dict] = attrs.field(alias="diversions", default=None, repr=False)
    diversions_ifno: Optional[NDArray[np.int64]] = array(
        block="diversions",
        dims=("nreaches",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="reach number for this entry",
        cellid=True,
    )
    idv: Optional[NDArray[np.int64]] = array(
        block="diversions",
        dims=("nreaches",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="downstream diversion number",
        cellid=True,
    )
    iconr: Optional[NDArray[np.int64]] = array(
        block="diversions",
        dims=("nreaches",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="downstream reach number for diversion",
        cellid=True,
    )
    cprior: Optional[NDArray[np.object_]] = array(
        block="diversions",
        dims=("nreaches",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="iprior code",
    )
    _initialstages: Optional[dict] = attrs.field(alias="initialstages", default=None, repr=False)
    initialstages_ifno: Optional[NDArray[np.int64]] = array(
        block="initialstages",
        dims=("nreaches",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="reach number for this entry",
        cellid=True,
    )
    initialstage: Optional[NDArray[np.float64]] = array(
        block="initialstages",
        dims=("nreaches",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="initial reach stage",
    )
    ifno: Optional[NDArray[np.int64]] = array(
        block="period",
        dims=("nper",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="reach number for this entry",
    )
    # TODO: sfrsetting — type 'union' not yet supported
    __block_col_maps__: ClassVar[dict] = {
        "packagedata": {
            "ifno": "packagedata_ifno",
            "cellid": "cellid",
            "rlen": "rlen",
            "rwid": "rwid",
            "rgrd": "rgrd",
            "rtp": "rtp",
            "rbth": "rbth",
            "rhk": "rhk",
            "man": "man",
            "ncon": "ncon",
            "ustrf": "ustrf",
            "ndv": "ndv",
            "aux": "aux",
            "boundname": "boundname",
        },
        "crosssections": {
            "ifno": "crosssections_ifno",
            "tab6_filename": "tab6_filename",
        },
        "connectiondata": {
            "ifno": "connectiondata_ifno",
            "ic": "ic",
        },
        "diversions": {
            "ifno": "diversions_ifno",
            "idv": "idv",
            "iconr": "iconr",
            "cprior": "cprior",
        },
        "initialstages": {
            "ifno": "initialstages_ifno",
            "initialstage": "initialstage",
        },
    }

    def __attrs_post_init__(self):
        if self.auxiliary is not None:
            _aux = self.auxiliary
            self.naux = int(_aux.values.size) if hasattr(_aux, "values") else len(_aux)
        if self._packagedata is not None:
            self._set_block(
                "packagedata",
                "nreaches",
                True,
                {
                    "ifno": "packagedata_ifno",
                    "cellid": "cellid",
                    "rlen": "rlen",
                    "rwid": "rwid",
                    "rgrd": "rgrd",
                    "rtp": "rtp",
                    "rbth": "rbth",
                    "rhk": "rhk",
                    "man": "man",
                    "ncon": "ncon",
                    "ustrf": "ustrf",
                    "ndv": "ndv",
                    "aux": "aux",
                    "boundname": "boundname",
                },
                self._packagedata,
            )
        if self._crosssections is not None:
            self._set_block(
                "crosssections",
                "nreaches",
                True,
                {
                    "ifno": "crosssections_ifno",
                    "tab6_filename": "tab6_filename",
                },
                self._crosssections,
            )
        if self._connectiondata is not None:
            self._set_block(
                "connectiondata",
                "nreaches",
                True,
                {
                    "ifno": "connectiondata_ifno",
                    "ic": "ic",
                },
                self._connectiondata,
            )
        if self._diversions is not None:
            self._set_block(
                "diversions",
                "nreaches",
                True,
                {
                    "ifno": "diversions_ifno",
                    "idv": "idv",
                    "iconr": "iconr",
                    "cprior": "cprior",
                },
                self._diversions,
            )
        if self._initialstages is not None:
            self._set_block(
                "initialstages",
                "nreaches",
                True,
                {
                    "ifno": "initialstages_ifno",
                    "initialstage": "initialstage",
                },
                self._initialstages,
            )

    @property
    def packagedata(self):
        return self._get_block(
            {
                "ifno": "packagedata_ifno",
                "cellid": "cellid",
                "rlen": "rlen",
                "rwid": "rwid",
                "rgrd": "rgrd",
                "rtp": "rtp",
                "rbth": "rbth",
                "rhk": "rhk",
                "man": "man",
                "ncon": "ncon",
                "ustrf": "ustrf",
                "ndv": "ndv",
                "aux": "aux",
                "boundname": "boundname",
            }
        )

    @packagedata.setter
    def packagedata(self, value) -> None:
        self._set_block(
            "packagedata",
            "nreaches",
            True,
            {
                "ifno": "packagedata_ifno",
                "cellid": "cellid",
                "rlen": "rlen",
                "rwid": "rwid",
                "rgrd": "rgrd",
                "rtp": "rtp",
                "rbth": "rbth",
                "rhk": "rhk",
                "man": "man",
                "ncon": "ncon",
                "ustrf": "ustrf",
                "ndv": "ndv",
                "aux": "aux",
                "boundname": "boundname",
            },
            value,
        )

    @property
    def crosssections(self):
        return self._get_block(
            {
                "ifno": "crosssections_ifno",
                "tab6_filename": "tab6_filename",
            }
        )

    @crosssections.setter
    def crosssections(self, value) -> None:
        self._set_block(
            "crosssections",
            "nreaches",
            True,
            {
                "ifno": "crosssections_ifno",
                "tab6_filename": "tab6_filename",
            },
            value,
        )

    @property
    def connectiondata(self):
        return self._get_block(
            {
                "ifno": "connectiondata_ifno",
                "ic": "ic",
            }
        )

    @connectiondata.setter
    def connectiondata(self, value) -> None:
        self._set_block(
            "connectiondata",
            "nreaches",
            True,
            {
                "ifno": "connectiondata_ifno",
                "ic": "ic",
            },
            value,
        )

    @property
    def diversions(self):
        return self._get_block(
            {
                "ifno": "diversions_ifno",
                "idv": "idv",
                "iconr": "iconr",
                "cprior": "cprior",
            }
        )

    @diversions.setter
    def diversions(self, value) -> None:
        self._set_block(
            "diversions",
            "nreaches",
            True,
            {
                "ifno": "diversions_ifno",
                "idv": "idv",
                "iconr": "iconr",
                "cprior": "cprior",
            },
            value,
        )

    @property
    def initialstages(self):
        return self._get_block(
            {
                "ifno": "initialstages_ifno",
                "initialstage": "initialstage",
            }
        )

    @initialstages.setter
    def initialstages(self, value) -> None:
        self._set_block(
            "initialstages",
            "nreaches",
            True,
            {
                "ifno": "initialstages_ifno",
                "initialstage": "initialstage",
            },
            value,
        )
