# autogenerated file, do not modify
# ruff: noqa: E501
from pathlib import Path
from typing import ClassVar, Optional

import attrs
import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, dim, field, path
from flopy4.utils import to_path


@xattree(kw_only=True)
class Uzf(Package):
    multi_package: ClassVar[bool] = True

    auxiliary: Optional[list[str]] = array(
        block="options", default=None, longname="keyword to specify aux variables"
    )
    auxmultname: Optional[str] = field(
        block="options", default=None, longname="name of auxiliary variable for multiplier"
    )
    boundnames: bool = field(block="options", default=False)
    print_input: bool = field(
        block="options", default=False, longname="print input to listing file"
    )
    print_flows: bool = field(
        block="options", default=False, longname="print calculated flows to listing file"
    )
    save_flows: bool = field(
        block="options", default=False, longname="save well flows to budget file"
    )
    wc_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    budget_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    budgetcsv_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    package_convergence_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    ts_file: Optional[Path] = path(block="options", default=None, converter=to_path, inout="filein")
    obs_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="filein"
    )
    mover: bool = field(block="options", default=False)
    simulate_et: bool = field(block="options", default=False)
    linear_gwet: bool = field(
        block="options", default=False, longname="use linear evapotranspiration"
    )
    square_gwet: bool = field(
        block="options", default=False, longname="use square evapotranspiration"
    )
    simulate_gwseep: bool = field(block="options", default=False, longname="activate seepage")
    unsat_etwc: bool = field(
        block="options", default=False, longname="use PET for theta greater than extwc"
    )
    unsat_etae: bool = field(block="options", default=False, longname="use root potential")
    nuzfcells: Optional[int] = dim(
        block="dimensions", coord=False, default=None, longname="number of UZF cells"
    )
    ntrailwaves: Optional[int] = dim(
        block="dimensions", coord=False, default="7", longname="number of trailing waves"
    )
    nwavesets: Optional[int] = dim(
        block="dimensions", coord=False, default="40", longname="number of wave sets"
    )
    _packagedata: Optional[dict] = attrs.field(alias="packagedata", default=None, repr=False)
    ifno: Optional[NDArray[np.int64]] = array(
        block="packagedata",
        dims=("nuzfcells",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="uzf id number for this entry",
        cellid=True,
    )
    cellid: Optional[NDArray[np.object_]] = array(
        block="packagedata",
        dims=("nuzfcells",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="cell identifier",
        cellid=True,
    )
    landflag: Optional[NDArray[np.int64]] = array(
        block="packagedata",
        dims=("nuzfcells",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="land flag",
    )
    ivertcon: Optional[NDArray[np.int64]] = array(
        block="packagedata",
        dims=("nuzfcells",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="vertical connection flag",
        cellid=True,
    )
    surfdep: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("nuzfcells",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="surface depression depth",
    )
    vks: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("nuzfcells",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="vertical saturated hydraulic conductivity",
    )
    thtr: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("nuzfcells",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="residual water content",
    )
    thts: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("nuzfcells",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="saturated water content",
    )
    thti: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("nuzfcells",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="initial water content",
    )
    eps: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("nuzfcells",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="Brooks-Corey exponent",
    )
    boundname: Optional[NDArray[np.object_]] = array(
        block="packagedata",
        dims=("nuzfcells",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="well name",
    )
    naux: Optional[int] = dim(block="__dim__", coord=False, default=None)
    finf: Optional[NDArray[np.object_]] = array(
        block="period",
        dims=("nper",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="infiltration rate",
    )
    pet: Optional[NDArray[np.object_]] = array(
        block="period",
        dims=("nper",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="potential ET rate",
    )
    extdp: Optional[NDArray[np.object_]] = array(
        block="period",
        dims=("nper",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="extinction depth",
    )
    extwc: Optional[NDArray[np.object_]] = array(
        block="period",
        dims=("nper",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="extinction water content",
    )
    ha: Optional[NDArray[np.object_]] = array(
        block="period",
        dims=("nper",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="air entry potential",
    )
    hroot: Optional[NDArray[np.object_]] = array(
        block="period",
        dims=("nper",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="root potential",
    )
    rootact: Optional[NDArray[np.object_]] = array(
        block="period",
        dims=("nper",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="root activity function",
    )
    aux: Optional[NDArray[np.float64]] = array(
        block="period",
        dims=("nper", "naux"),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="auxiliary variables",
    )
    __block_col_maps__: ClassVar[dict] = {
        "packagedata": {
            "ifno": "ifno",
            "cellid": "cellid",
            "landflag": "landflag",
            "ivertcon": "ivertcon",
            "surfdep": "surfdep",
            "vks": "vks",
            "thtr": "thtr",
            "thts": "thts",
            "thti": "thti",
            "eps": "eps",
            "boundname": "boundname",
        },
    }

    def __attrs_post_init__(self):
        if self.auxiliary is not None:
            _aux = self.auxiliary
            self.naux = int(_aux.values.size) if hasattr(_aux, "values") else len(_aux)
        if self._packagedata is not None:
            self._set_block(
                "packagedata",
                "nuzfcells",
                True,
                {
                    "ifno": "ifno",
                    "cellid": "cellid",
                    "landflag": "landflag",
                    "ivertcon": "ivertcon",
                    "surfdep": "surfdep",
                    "vks": "vks",
                    "thtr": "thtr",
                    "thts": "thts",
                    "thti": "thti",
                    "eps": "eps",
                    "boundname": "boundname",
                },
                self._packagedata,
            )

    @property
    def packagedata(self):
        return self._get_block(
            {
                "ifno": "ifno",
                "cellid": "cellid",
                "landflag": "landflag",
                "ivertcon": "ivertcon",
                "surfdep": "surfdep",
                "vks": "vks",
                "thtr": "thtr",
                "thts": "thts",
                "thti": "thti",
                "eps": "eps",
                "boundname": "boundname",
            }
        )

    @packagedata.setter
    def packagedata(self, value) -> None:
        self._set_block(
            "packagedata",
            "nuzfcells",
            True,
            {
                "ifno": "ifno",
                "cellid": "cellid",
                "landflag": "landflag",
                "ivertcon": "ivertcon",
                "surfdep": "surfdep",
                "vks": "vks",
                "thtr": "thtr",
                "thts": "thts",
                "thti": "thti",
                "eps": "eps",
                "boundname": "boundname",
            },
            value,
        )
