# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional, Union

from pydantic import SkipValidation
from pydantic.dataclasses import dataclass

from flopy4.mf6._types import _optional_path
from flopy4.mf6.item import Item
from flopy4.mf6.package import CFG, Package
from flopy4.mf6.spec import field, path


@dataclass(config=CFG, kw_only=True)
class Vsc(Package):
    dfn_name: ClassVar[str] = "gwf-vsc"

    @dataclass(config=CFG)
    class Packagedata(Item):
        iviscspec: int = field(index=True, pk=True)
        dviscdc: float = field()
        cviscref: float = field()
        modelname: Union[float, str] = field()
        auxspeciesname: Union[float, str] = field()
        aux: tuple = ()

    viscref: Optional[float] = field(
        default=1.0,
        block="options",
        optional=True,
    )
    temperature_species_name: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
    )
    thermal_formulation: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
    )
    thermal_a2: Optional[float] = field(
        default=10.0,
        block="options",
        optional=True,
    )
    thermal_a3: Optional[float] = field(
        default=248.37,
        block="options",
        optional=True,
    )
    thermal_a4: Optional[float] = field(
        default=133.15,
        block="options",
        optional=True,
    )
    viscosity_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
    )
    nviscspecies: Optional[int] = field(
        default=None,
        block="dimensions",
    )
    packagedata: Optional[SkipValidation[list[Packagedata]]] = field(
        default=None,
        block="packagedata",
        auto_from="packagedata",
    )

VscPackagedata = Vsc.Packagedata
